POST http://localhost:4000/backend/userSignup

###

POST http://localhost:4000/backend/userLogin
Content-Type: application/json

{
  "username": "jeffrey@xyma.in",
  "password": "your_password_here"
}
###

POST http://localhost:4000/backend/refreshToken
###

DELETE http://localhost:4000/backend/logout
###

GET  http://localhost:4000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzgxNDk4NjcsImV4cCI6MTczODE1MTY2NywiYXVkIjoiNjc4ZGZiMDkzZWExOWE2YTQ2YzM5ZTI0IiwiaXNzIjoieHltYSJ9.dFmSfxxd9NB5bj8cl_CTE3M2k2GFxa9q-2vWI4q2IdA